public import OpenAPIRuntime

// WireOpenAPI — collation for OpenAPI controllers. `@OpenAPIController` types are collated onto one
// generated proxy per spec, which contributes to **`WireMVCKeys.routeContributors`**: an operation is a
// route like any other, serving under the same router, `@NotFound` fallback, `@ErrorResponse` tiers,
// global middleware layer and `@WireMVCBootstrap` composition root as an annotation-driven `@Get`. One
// routing model, not two.
//
// M3 collated into a separate `TransportKeys.handlers` with its own `TransportComposable` conformance
// and a `WireOpenAPI.apply` facade. All three are retired (M6d.1b). The two surfaces are
// inter-convertible — `WireMVCServerTransport` carries routes out onto a transport, `WireOpenAPIRoutes`
// carries transport registrations in as routes — so two collation keys were duplication.
//
// **Serving on a foreign transport is `WireMVCServerTransport.apply(graph, to: transport)`**, the same
// call a WireMVC app already makes: it registers every collated route uniformly and bridges the lot.
// A WireOpenAPI-specific facade would have had to filter the route collection by conformance, silently
// dropping the app's `@Controller` routes — and would double-register if used alongside the correct
// call. There is one path, and it is not this module's.

/// A transport contributor. `registerWireHandlers` is generated by `@OpenAPIController`
/// — it owns the mount (an optional base path) and delegates to the generated
/// `registerHandlers(on:)`. Not intended to be written by hand (the `Wire` in the name
/// marks it generated).
///
/// `Sendable` because a controller is an app-scoped singleton whose handlers run
/// concurrently per request — it's shared across isolation domains already. Requiring it
/// here also keeps the generated graph `Sendable`, so it can be handed to a
/// `ServiceGroup` / `WireHummingbird.teardownService`.
public protocol TransportContributor: Sendable {
    func registerWireHandlers(on transport: any ServerTransport) throws
}

// `TransportKeys.handlers` retired in M6d.1b. Operations collate into `WireMVCKeys.routeContributors`
// instead — the fold M3's "WireMVC seam" section asked for, in the direction the evidence supports.
// `TransportContributor` stays because it is exactly the shape `registerHandlers` needs: the collecting
// transport consumes it, and the generated proxies conform to it so their operations can be replayed.
