import Foundation
import SwiftParser
import SwiftSyntax
import Yams

// WireOpenAPIGen — the domain half of WireOpenAPI's codegen, the counterpart to WireMVC's
// `WireMVCRouteGen`.
//
// swift-wire's WireGen emits the *structural* half of the contributor proxy: the struct, its fields
// (`_wireSubject`, or `_wireSubject_<Subject>` when a group holds several), its initialiser, and
// `Sendable` — with a body hole. This tool fills that hole with the `TransportContributor` conformance
// whose witness calls the OpenAPI generator's `registerHandlers`.
//
// It cannot live in the `@OpenAPIController` macro. `TransportContributor` refines `Sendable`, and Swift
// requires a `Sendable` conformance in the type's own file, so the conformance can only be attached to a
// type declared in the same generated module — the proxy — which the macro cannot see.
//
// Usage: WireOpenAPIGen <output.swift> [--spec <openapi.yaml>] [--import <Module>]... [--module <Name> <source.swift>...]...
//
// Each proxy gets BOTH conformances, unconditionally. `RouteContributor` is what the proxy is collated
// as — operations are routes, serving under the same router, `@NotFound`, error tiers and composition
// root as annotation-driven ones. `TransportContributor` is the shape `registerHandlers` needs, used by
// the route registration itself, which replays it against a collecting transport.

// MARK: - argument parsing

var arguments = Array(CommandLine.arguments.dropFirst())
guard let outputPath = arguments.first else {
    FileHandle.standardError.write(Data("WireOpenAPIGen: missing output path\n".utf8))
    exit(1)
}
arguments.removeFirst()

var imports: [String] = []
var specPaths: [String] = []
var sourcePaths: [String] = []
var index = 0
while index < arguments.count {
    switch arguments[index] {
    case "--spec":
        index += 1
        if index < arguments.count { specPaths.append(arguments[index]) }
    case "--import":
        index += 1
        if index < arguments.count { imports.append(arguments[index]) }
    case "--module":
        index += 1  // the module name itself is not needed: the emitted extension is module-local
    default:
        sourcePaths.append(arguments[index])
    }
    index += 1
}

let discovered = discoverControllers(in: sourcePaths)

// MARK: - grouping

/// The proxy type swift-wire synthesises for a group — `_WireOpenAPIContributor` for the default group,
/// `_WireOpenAPIContributor_<Spec>` otherwise. Must match `aggregateProxyTypeName` in WireGenCore.
func proxyTypeName(for spec: String?) -> String {
    guard let spec, !spec.isEmpty else { return "_WireOpenAPIContributor" }
    let sanitised = String(spec.map { $0.isLetter || $0.isNumber ? $0 : "_" })
    return "_WireOpenAPIContributor_\(sanitised)"
}

var byGroup: [String: [DiscoveredController]] = [:]
for controller in discovered {
    byGroup[controller.spec ?? "", default: []].append(controller)
}

// One conformer per spec is not a preference — `registerHandlers` is generated once per document and
// registers every operation from a single handler, so two controllers on one spec would each register the
// whole spec. Splitting a spec across controllers needs the proxy to *implement* `APIProtocol` and
// dispatch per operation, which is a later milestone; until then this is a hard error rather than silent
// double registration.
for (spec, controllers) in byGroup where controllers.count > 1 {
    let named = controllers.map(\.typeName).sorted().joined(separator: ", ")
    let label = spec.isEmpty ? "the default spec" : "spec '\(spec)'"
    let location = controllers[0]
    FileHandle.standardError.write(
        Data(
            """
            \(location.file):\(location.line): error: \(controllers.count) @OpenAPIController types share \
            \(label) (\(named)). The OpenAPI generator emits one registerHandlers per document, so each \
            would register every operation. Give them distinct `spec:` values, or wait for generated \
            per-operation dispatch.

            """.utf8
        )
    )
    exit(1)
}

// What the document says: the prefix operations register under, and where each operationId lands.
let serverPrefix = resolveServerPrefix(specPaths: specPaths)
let operationRoutes = resolveOperationRoutes(specPaths: specPaths)

// MARK: - emission

// `WireOpenAPI` and `OpenAPIRuntime` are always needed (the conformance and its `ServerTransport`
// parameter); a Wire-aware dependency may name either, so the set is deduplicated rather than appended —
// a repeated import compiles but reads like a codegen bug.
let allImports = Set(["Foundation", "OpenAPIRuntime", "WireMVC", "WireOpenAPI"] + imports).sorted()
var lines: [String] = ["// Generated by WireOpenAPIGen — do not edit.", ""]
lines += allImports.map { "import \($0)" }
lines.append("")

let serverURLArgument = serverPrefix == .none ? "" : ", serverURL: try Servers.Server1.url()"

for (spec, controllers) in byGroup.sorted(by: { $0.key < $1.key }) {
    guard let controller = controllers.first else { continue }
    let proxy = proxyTypeName(for: spec.isEmpty ? nil : spec)

    // Controller-scope `@Middleware`, folded around every operation of this spec. The fold is emitted
    // *here* rather than run from a helper because `wireCompose` returns the chain's concrete composed
    // type — erasing it would stop the terminal reading the final box's contents.
    //
    // Each entry names a field Wire has already lifted onto the proxy: `T.self` injects the binding by
    // type, a `FactoryKey` a synthesised factory whose `create` is specialised at the builder's box
    // roles. Same spelling WireMVC's route codegen uses, so one `@Middleware(RequireAPIKey.self)`
    // component serves an operation and a `@Get` alike.
    func foldEntries(_ arguments: [String], indent: String) -> [String] {
        arguments.map { argument in
            if argument.hasSuffix(".self") {
                return indent + "self.\(dependencyPropertyName(forType: String(argument.dropLast(5))))"
            }
            return indent + "self._wireFactory_\(sanitizedKeyFragment(argument))"
                + ".create(Builder.RequestContext.self, Builder.Reader.self, Builder.ResponseSender.self)"
        }
    }

    // Controller-scope entries fold *outside* route-scope ones, matching WireMVC's ordering
    // (controller-outer → route-inner → handler).
    let controllerEntries = foldEntries(controller.middleware, indent: "            ")

    // Route-scope middleware needs each method matched to the route its operation registers as. The
    // collector reports only (method, path), so the document supplies the mapping — and a method whose
    // operationId the document doesn't declare is an error rather than middleware that silently never
    // runs, which is the failure the marker exists to prevent.
    var routeCases: [(route: OperationRoute, entries: [String])] = []
    for operation in controller.operations where !operation.middleware.isEmpty {
        guard let route = operationRoutes[operation.operationID] else {
            FileHandle.standardError.write(
                Data(
                    """
                    \(controller.file):\(controller.line): error: @RawOperation \
                    '\(operation.operationID)' carries @Middleware but the document declares no such \
                    operationId. Name the operation it implements — @RawOperation("the-id") — or remove \
                    the middleware.

                    """.utf8
                )
            )
            exit(1)
        }
        routeCases.append((route: route, entries: foldEntries(operation.middleware, indent: "                    ")))
    }
    /// One `builder.register` call, wrapped in `entries` if there are any. The fold is emitted inline
    /// rather than hoisted because `wireCompose` returns the chain's concrete composed type — the thing
    /// that lets the terminal read the final box's contents.
    func registerBlock(entries: [String], indent: String) -> String {
        guard !entries.isEmpty else {
            return """
                \(indent)builder.register(method: wireOpenAPIRoute.method, path: wireOpenAPIRoute.path) { request, _, parameters, reader, sender in
                \(indent)    try await WireOpenAPIRoutes.invoke(
                \(indent)        wireOpenAPIRoute, request: request, pathParameters: parameters,
                \(indent)        reader: reader, sender: sender
                \(indent)    )
                \(indent)}
                """
        }
        return """
            \(indent)builder.register(method: wireOpenAPIRoute.method, path: wireOpenAPIRoute.path) {
            \(indent)    request, requestContext, parameters, reader, responseSender in
            \(indent)    let wireOpenAPIBox = RequestResponseMiddlewareBox.pending(
            \(indent)        request: request, requestContext: requestContext, reader: reader,
            \(indent)        responseSender: responseSender
            \(indent)    )
            \(indent)    let wireOpenAPIChain = wireCompose {
            \(entries.joined(separator: "\n"))
            \(indent)    }
            \(indent)    try await wireOpenAPIChain.intercept(input: wireOpenAPIBox) { wireOpenAPIFinalBox in
            \(indent)        try await wireOpenAPIFinalBox.withPendingContents { request, _, reader, responseSender in
            \(indent)            try await WireOpenAPIRoutes.invoke(
            \(indent)                wireOpenAPIRoute, request: request, pathParameters: parameters,
            \(indent)                reader: reader, sender: responseSender
            \(indent)            )
            \(indent)        }
            \(indent)    }
            \(indent)}
            """
    }

    // With no route-scope middleware every operation takes the same chain, so one register call in the
    // loop suffices. With it, operations differ, and each needs its own fold — hence a switch on the
    // route the document says the operation registers as.
    let registrations: String
    var unmatchedDeclaration = ""
    var unmatchedCheck = ""
    if routeCases.isEmpty {
        registrations = registerBlock(entries: controllerEntries, indent: "            ")
    } else {
        var branches: [String] = []
        for entry in routeCases {
            branches.append("            case (\"\(entry.route.method)\", \"\(entry.route.path)\"):")
            branches.append(
                "                wireOpenAPIUnmatched.remove(\"\(entry.route.method) \(entry.route.path)\")"
            )
            branches.append(registerBlock(entries: controllerEntries + entry.entries, indent: "                "))
        }
        branches.append("            default:")
        branches.append(registerBlock(entries: controllerEntries, indent: "                "))
        let declared = routeCases.map { "\"\($0.route.method) \($0.route.path)\"" }
        registrations = """
                    switch (wireOpenAPIRoute.method.rawValue, wireOpenAPIRoute.path) {
            \(branches.joined(separator: "\n"))
                    }
            """
        // Guard the composition: this package derives the registered path from the document, while the
        // generated `registerHandlers` derives it inside `apiPathComponentsWithServerPrefix`. If those
        // ever disagree the switch quietly takes `default` and the route's middleware vanishes, so the
        // witness fails at startup instead, naming what would have been dropped.
        unmatchedDeclaration = "        var wireOpenAPIUnmatched: Set<String> = [\(declared.joined(separator: ", "))]"
        // The description is written to stderr before the throw. Registration happens after the server is
        // constructed, so an error thrown out of the generated `@main` races the server's teardown — NIO
        // traps on its leaking promise first and the error is never printed. A misconfiguration the
        // developer cannot see is barely better than one that fails silently.
        unmatchedCheck = """
                    if !wireOpenAPIUnmatched.isEmpty {
                        let wireOpenAPIError = WireOpenAPIRoutes.RouteMismatch(
                            operations: wireOpenAPIUnmatched.sorted()
                        )
                        FileHandle.standardError.write(Data((wireOpenAPIError.description + "\\n").utf8))
                        throw wireOpenAPIError
                    }
            """
    }

    // The shape `registerHandlers` needs. At one subject the aggregate keeps the singular `_wireSubject`
    // field, so the witness delegates to the controller's own generated registration — under the
    // document's own server prefix, which has to be passed explicitly (see `ServerPrefix`).
    lines.append(
        """
        extension \(proxy): TransportContributor {
            func registerWireHandlers(on transport: any ServerTransport) throws {
                try _wireSubject.registerHandlers(on: transport\(serverURLArgument))
            }
        }
        """
    )
    lines.append("")

    // The conformance the proxy is *collated* as. It delegates to the witness above: the operation set
    // is discovered by running the generator's own registration against a collector, so there is no
    // per-operation codegen here.
    lines.append(
        """
        extension \(proxy): RouteContributor {
            func registerWireRoutes<Builder: HTTPServerRouteBuilder>(on builder: inout Builder) throws
            where
                Builder.RequestContext: ~Copyable & SendableMetatype,
                Builder.Reader: ~Copyable,
                Builder.ResponseSender: ~Copyable,
                Builder.ResponseSender.Writer: ~Copyable
            {
        \(unmatchedDeclaration)
                for wireOpenAPIRoute in try WireOpenAPIRoutes.operations(of: self) {
        \(registrations)
                }
        \(unmatchedCheck)
            }
        }
        """
    )
    lines.append("")
}

try (lines.joined(separator: "\n")).write(toFile: outputPath, atomically: true, encoding: .utf8)
