import Foundation
import SwiftParser
import SwiftSyntax
import Yams

// WireOpenAPIGen — the domain half of WireOpenAPI's codegen, the counterpart to WireMVC's
// `WireMVCRouteGen`.
//
// swift-wire's WireGen emits the *structural* half of the contributor proxy: the struct, its fields
// (`_wireSubject`, or `_wireSubject_<Subject>` when a group holds several), its initialiser, and
// `Sendable` — with a body hole. This tool fills that hole with the `RouteContributor` conformance that
// mounts the spec's operations as WireMVC routes.
//
// It cannot live in the `@OpenAPIController` macro. `RouteContributor` refines `Sendable`, and Swift
// requires a `Sendable` conformance in the type's own file, so the conformance can only be attached to a
// type declared in the same generated module — the proxy — which the macro cannot see.
//
// Usage: WireOpenAPIGen <output.swift> [--spec <openapi.yaml>] [--import <Module>]... [--module <Name> <source.swift>...]...
//
// The proxy is collated as a `RouteContributor` and nothing else: operations are routes, serving under
// the same router, `@NotFound`, error tiers and composition root as annotation-driven ones.

// MARK: - argument parsing

var arguments = Array(CommandLine.arguments.dropFirst())
guard let outputPath = arguments.first else {
    FileHandle.standardError.write(Data("WireOpenAPIGen: missing output path\n".utf8))
    exit(1)
}
arguments.removeFirst()

var imports: [String] = []
var specPaths: [String] = []
var sourcePaths: [String] = []
var index = 0
while index < arguments.count {
    switch arguments[index] {
    case "--spec":
        index += 1
        if index < arguments.count { specPaths.append(arguments[index]) }
    case "--import":
        index += 1
        if index < arguments.count { imports.append(arguments[index]) }
    case "--module":
        index += 1  // the module name itself is not needed: the emitted extension is module-local
    default:
        sourcePaths.append(arguments[index])
    }
    index += 1
}

let discovered = discoverControllers(in: sourcePaths)

// MARK: - grouping

/// The proxy type swift-wire synthesises for a group — `_WireOpenAPIContributor` for the default group,
/// `_WireOpenAPIContributor_<Spec>` otherwise. Must match `aggregateProxyTypeName` in WireGenCore.
func proxyTypeName(for spec: String?) -> String {
    guard let spec, !spec.isEmpty else { return "_WireOpenAPIContributor" }
    let sanitised = String(spec.map { $0.isLetter || $0.isNumber ? $0 : "_" })
    return "_WireOpenAPIContributor_\(sanitised)"
}

var byGroup: [String: [DiscoveredController]] = [:]
for controller in discovered {
    byGroup[controller.spec ?? "", default: []].append(controller)
}

// What the document says: the prefix operations register under, and where each operationId lands.
let serverPrefix = resolveServerPrefix(specPaths: specPaths)
let operationRoutes = resolveOperationRoutes(specPaths: specPaths)

// MARK: - emission

// `WireOpenAPI` and `OpenAPIRuntime` are always needed (the conformance and the server it dispatches
// through); a Wire-aware dependency may name either, so the set is deduplicated rather than appended — a
// repeated import compiles but reads like a codegen bug.
//
// `UniversalServer` is `@_spi(Generated)`, the same import the generator's own `Server.swift` writes.
let allImports = Set(["Foundation", "OpenAPIRuntime", "WireMVC", "WireOpenAPI"] + imports).sorted()
var lines: [String] = ["// Generated by WireOpenAPIGen — do not edit.", ""]
lines += allImports.map { $0 == "OpenAPIRuntime" ? "@_spi(Generated) import \($0)" : "import \($0)" }
lines.append("")

// A `@Middleware` fold. Each entry names a field Wire has already lifted onto the proxy: `T.self`
// injects the binding by type, a `FactoryKey` a synthesised factory whose `create` is specialised at the
// builder's box roles. Same spelling WireMVC's route codegen uses, so one `@Middleware(RequireAPIKey.self)`
// component serves an operation and a `@Get` alike.
//
// It is emitted at each registration rather than run from a helper because `wireCompose` returns the
// chain's concrete composed type — erasing it would stop the terminal reading the final box's contents.
func foldEntries(_ arguments: [String], indent: String) -> [String] {
    arguments.map { argument in
        if argument.hasSuffix(".self") {
            return indent + "self.\(dependencyPropertyName(forType: String(argument.dropLast(5))))"
        }
        return indent + "self._wireFactory_\(sanitizedKeyFragment(argument))"
            + ".create(Builder.RequestContext.self, Builder.Reader.self, Builder.ResponseSender.self)"
    }
}

for (spec, controllers) in byGroup.sorted(by: { $0.key < $1.key }) where !controllers.isEmpty {
    DirectDispatchEmitter(
        spec: spec,
        proxy: proxyTypeName(for: spec.isEmpty ? nil : spec),
        controllers: controllers,
        operationRoutes: operationRoutes,
        serverPrefix: serverPrefix,
        foldEntries: foldEntries
    ).emit(into: &lines)
}

try (lines.joined(separator: "\n")).write(toFile: outputPath, atomically: true, encoding: .utf8)
