#!/usr/bin/env python3
"""Regenerate (or check) the naming golden table from the *real* swift-openapi-generator.

`Sources/WireOpenAPINaming/GeneratorSafeNames.swift` is a transcription of the generator's internal
`SafeNameGenerator`. A copied algorithm does not fail when it is wrong today — it fails when the original
changes and ours does not, and the symptom is "cannot find type `Operations.Foo`" inside generated code.

So the table this writes is produced by running the generator itself: a corpus document whose operationIds
and parameter names cover the interesting shapes, generated under both naming strategies, with the names
it actually emitted read back out. The unit tests assert our transcription reproduces this table; CI runs
this script with `--check`, so a generator bump that changes naming fails with a name-by-name diff.

    Scripts/refresh-naming-golden.py            # rewrite the table
    Scripts/refresh-naming-golden.py --check    # fail if the generator no longer agrees with it

The generator is located via OPENAPI_GENERATOR_PATH, defaulting to the checkout the Fixtures package
already resolves.
"""

import os
import re
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GOLDEN = os.path.join(ROOT, "Tests", "WireOpenAPINamingTests", "naming-golden.tsv")
CORPUS = os.path.join(ROOT, "Tests", "WireOpenAPINamingTests", "naming-corpus.txt")
GENERATOR = os.environ.get(
    "OPENAPI_GENERATOR_PATH",
    os.path.join(ROOT, "Fixtures", ".build", "checkouts", "swift-openapi-generator"),
)


def corpus():
    """The documented names under test: one list, used both as operationIds and as parameter names."""
    with open(CORPUS) as f:
        return [line for line in (l.rstrip("\n") for l in f) if line and not line.startswith("#")]


def write_document(path, names):
    """One operation per name (for type names), plus one path parameter per name (for member names).

    A parameter name goes in the path template, so names containing `{`, `}` or `/` cannot be used as
    parameters; they are still exercised as operationIds.
    """
    lines = ["openapi: 3.1.0", "info: { title: Naming, version: 1.0.0 }", "paths:"]
    param_names = []
    for i, name in enumerate(names):
        lines.append(
            f"  /op{i}:\n    get:\n      operationId: {name!r}\n"
            f"      responses: {{ '200': {{ description: ok }} }}"
        )
    for i, name in enumerate(names):
        if any(c in name for c in "{}/"):
            continue
        param_names.append((i, name))
        lines.append(
            f"  /p{i}/{{{name}}}:\n    get:\n      operationId: param{i}\n"
            f"      parameters:\n        - name: {name!r}\n          in: path\n"
            f"          required: true\n          schema: {{ type: string }}\n"
            f"      responses: {{ '200': {{ description: ok }} }}"
        )
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    return param_names


def generate(workdir, document, strategy):
    config = os.path.join(workdir, f"config-{strategy}.yaml")
    with open(config, "w") as f:
        f.write(f"generate:\n  - types\naccessModifier: internal\nnamingStrategy: {strategy}\n")
    out = os.path.join(workdir, f"out-{strategy}")
    os.makedirs(out, exist_ok=True)
    result = subprocess.run(
        ["swift", "run", "--package-path", GENERATOR, "swift-openapi-generator",
         "generate", "--config", config, "--output-directory", out, document],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        sys.exit(f"generator failed for {strategy}:\n{result.stderr[-2000:]}")
    with open(os.path.join(out, "Types.swift")) as f:
        return f.read()


def extract(src, names, param_names):
    """(operationId -> Operations namespace, parameter name -> Path member) as the generator emitted them."""
    types = dict(
        re.findall(r"Generated from `#/paths/[^`]*?\(([^)]*)\)`\.\s*\n\s*internal enum (\w+)", src)
    )
    members = {}
    for i, name in param_names:
        block = re.search(
            r"internal enum [Pp]aram%d\b.*?internal struct Path: Sendable, Hashable \{(.*?)\n            \}" % i,
            src, re.S,
        )
        if not block:
            continue
        member = re.search(r"internal var (\w+):", block.group(1))
        if member:
            members[name] = member.group(1)
    return types, members


def build_table():
    names = corpus()
    with tempfile.TemporaryDirectory() as workdir:
        document = os.path.join(workdir, "openapi.yaml")
        param_names = write_document(document, names)
        rows = ["# documented\tdefensive.type\tdefensive.member\tidiomatic.type\tidiomatic.member",
                "# Generated by Scripts/refresh-naming-golden.py from the real swift-openapi-generator.",
                "# '-' means the shape cannot appear in that position (parameters live in a path template)."]
        extracted = {}
        for strategy in ("defensive", "idiomatic"):
            extracted[strategy] = extract(generate(workdir, document, strategy), names, param_names)
        for name in names:
            dt, dm = extracted["defensive"]
            it, im = extracted["idiomatic"]
            if name not in dt or name not in it:
                sys.exit(f"generator produced no type name for {name!r}; corpus or extraction is wrong")
            rows.append(
                "\t".join([name, dt[name], dm.get(name, "-"), it[name], im.get(name, "-")])
            )
    return "\n".join(rows) + "\n"


def main():
    table = build_table()
    if "--check" in sys.argv:
        with open(GOLDEN) as f:
            current = f.read()
        if current != table:
            print("The generator no longer agrees with the checked-in naming golden table.")
            print("Sources/WireOpenAPINaming is a copy of its internal transform; it has diverged.\n")
            import difflib
            sys.stdout.writelines(
                difflib.unified_diff(
                    current.splitlines(keepends=True), table.splitlines(keepends=True),
                    fromfile="naming-golden.tsv (checked in)", tofile="generator output (now)",
                )
            )
            sys.exit(1)
        print(f"naming golden table matches the generator ({len(corpus())} names).")
        return
    with open(GOLDEN, "w") as f:
        f.write(table)
    print(f"wrote {GOLDEN} ({len(corpus())} names).")


if __name__ == "__main__":
    main()
